#! /usr/bin/env node
/* jshint node:true, esnext:true, unused:true */
// vim: filetype=javascript
/*
 * bbuggy - a NodeJS Jabber+IRC bugbot.
 * Copyright (C) 2013-2014 Adrian Perez <aperez@igalia.com>
 *
 * Distributed under terms of the MIT license.
 */

"use strict";

const druid = require("./druid.js");
const config = require("./config.json");

let bot = new druid.Bot();
bot.addPlugin("googlecode", config.googlecode);
bot.addPlugin("bugzilla", config.bugzilla);
bot.addConnection(new druid.xmpp.XmppConnection(config.xmpp));
bot.addConnection(new druid.irc.IrcConnection(config.irc));
bot.run();
