#! /usr/bin/env node
/*
 * bbuggy - a NodeJS Jabber bugbot.
 * Copyright (C) 2013 Adrian Perez <aperez@igalia.com>
 *
 * Distributed under terms of the MIT license.
 */

const config = require("./config.json");
const druid = require("./druid.js");

// TODO Remove this from here and read this from config.json
const bzMapping = {
  "gnome": config.bugzilla.gb,
  "webkit": config.bugzilla.wk,
  "wk": config.bugzilla.wk,
  "fdo": config.bugzilla.fdo,
  "poppler": config.bugzilla.fdo,
  "freedesktop": config.bugzilla.fdo,
};


bot = new druid.Bot(config);

if (config.bugzilla)
  require("./bugzilla").configure(bot, config.bugzilla, bzMapping, "gnome");
if (config.googlecode)
  require("./googlecode").configure(bot, config.googlecode);

bot.run();

// vim: ft=javascript
